openapi: 3.0.3
components:
  schemas:
    ErrorResponse:
      properties:
        message:
          type: string
          example: Hopefully meaningful error message
    AuthRequest:
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: user@example.com
        password:
          type: string
          example: PWrkXdn6fB8e
    AuthResponse:
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              example: 82bf1932-4ac0-43f2-8173-15a3200650cc
            accessToken:
              type: string
              example: >-
                eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyYmYxOTMyLTRhYzAtNDNmMi04MTczLTE1YTMyMDA2NTBjYyIsImlhdCI6MTcwMDQwNzA3MywiZXhwIjoxNzAwNDEwNjczfQ.rJ_DCPt5H2P-PgOapfm8gZUKsmhUbxVvAvCI0cRvuiQ
            refreshToken:
              type: string
              example: >-
                eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyYmYxOTMyLTRhYzAtNDNmMi04MTczLTE1YTMyMDA2NTBjYyIsImlhdCI6MTcwMDQwNzA3MywiZXhwIjoxNzAwNDkxMDczfQ.zJ1oqdZ01Hpwq9rdd7kCbCjpGsAUGEJpc9SAYuCYTtg
    ShortenRequest:
      required:
        - url
      properties:
        url:
          type: string
          example: https://www.example.com
        daysToExpire:
          type: integer
          enum:
            - 1
            - 3
            - 7
    ShortenResponse:
      properties:
        data:
          type: object
          properties:
            linkId:
              type: string
              example: Ab01-_
            origin:
              type: string
              example: https://www.example.com
            link:
              type: string
              example: https://shortlinker.com/Ab01-_
    GetLinksResponse:
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: Ab01-_
              visitCount:
                type: integer
                example: 27
              userId:
                type: string
                example: 82bf1932-4ac0-43f2-8173-15a3200650cc
              origin:
                type: string
                example: https://www.example.com
              isActive:
                type: integer
                example: 1
              createdAt:
                type: string
                example: '2021-07-11T12:00:00.000Z'
              expiresAt:
                type: string
                example: '2021-07-18T12:00:00.000Z'
    DeactivateLinkResponse:
      properties:
        data:
          type: object
          properties:
            message:
              type: string
              example: Link deactivated successfully
    id:
      type: string
  securitySchemes:
    jwtAuthorizer:
      description: JWT authorization token (also referred to as access token)
      type: apiKey
      name: Authorization
      in: header
info:
  title: Shortlinker
  description: Serverless URL Shortener API
  version: 1.0.0
paths:
  /auth/sign-up:
    post:
      summary: Sign up
      description: >-
        Sign up function, which creates a new user and returns user id, access
        and refresh tokens
      operationId: authSignUp
      parameters: []
      tags: []
      requestBody:
        description: Sign up request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Sign up response body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          headers: {}
        '401':
          description: Request body is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '409':
          description: User with this email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
  /auth/sign-in:
    post:
      summary: Sign in
      description: Sign in function, which returns access and refresh tokens
      operationId: authSignIn
      parameters: []
      tags: []
      requestBody:
        description: Sign in request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Sign in response body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          headers: {}
        '401':
          description: Request body or credentials are invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
  /links:
    put:
      summary: Shorten URL
      description: >-
        Shorten URL function, which creates a new link and returns link id,
        origin and short link
      operationId: linksPut
      parameters: []
      tags: []
      security:
        - jwtAuthorizer: []
      requestBody:
        description: Shorten URL request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenRequest'
      responses:
        '200':
          description: Shorten URL response body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenResponse'
          headers: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '422':
          description: Request body is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
    get:
      summary: Get the list of your links
      description: Get all links function, which returns all links the user has created
      operationId: linksList
      parameters: []
      tags: []
      security:
        - jwtAuthorizer: []
      responses:
        '200':
          description: Get all links response body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLinksResponse'
          headers: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
  /links/{id}:
    patch:
      summary: Deactivate link
      description: Deactivate link function, which deactivates a link you have created
      operationId: linksDeactivate
      parameters:
        - name: id
          in: path
          description: Id of a previously shortened link
          required: true
          schema:
            $ref: '#/components/schemas/id'
      tags: []
      security:
        - jwtAuthorizer: []
      responses:
        '200':
          description: Deactivate link response body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeactivateLinkResponse'
          headers: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '404':
          description: Link not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
